### ISSUE TITLE
Sending Ripple

### ISSUE THREAD

**Issue by mserel** [rippex/ripple-client-desktop#13]
Payment failed? I'm sending to an account I just received from.

**Comment by vidalfontoura** [comment]
all operations  that I try  to execute within the ripple desktop wallet are falling or nothing happens (send,trade, create trust lines)

**Comment by marsface** [comment]
Hi guys, looks like it is a connectivity issues on the ripple network + the increase in the load. Ripple team said they are working on a solution for this and a new version of rippled should be released soon.

**Comment by marsface** [comment]
https://www.xrpchat.com/topic/4372-about-time-to-scale-rcl/?page=4#comment-43141

**Comment by marsface** [comment]
It should be solved now.

**Comment by mserel** [comment]
Still not working....

**Comment by mserel** [comment]
nevermind it is now!

**Comment by vidalfontoura** [comment]
YEahhhh. That work for me as well
