### ISSUE TITLE
cant access wallet if i move file location on file system

### ISSUE THREAD

**Issue by laurencefass** [rippex/ripple-client-desktop#15]
the wallet appears to tie wallet files to a fixed folder location on the file system. 

problem caused because i moved the folder I selected on file creation. returning to original location allows me correct access. i assume that the wallet file created on new account creation is used to read password,

the software's utility is limited if i cant change location of a wallet file once created. other desktop wallets simply allow user to select a credentials file prior to opening the wallet.

**Comment by laurencefass** [comment]
problem caused because i moved the folder I selected on file creation. returning to original location allows me correct access. i assume that the wallet file created on new account creation is used to read password, 

the software's utility is limited if i cant change location of a wallet file once created. other desktop wallets simply allow user to select a credentials file prior to opening the wallet.

how do i move a wallet file on my file system?

**Comment by laurencefass** [comment]
how do i move a wallet file on my file system? or

how do i get the wallet software to ask me where it is?

**Comment by marsface** [comment]
I could not reproduce this bug after moving 5 files to different locations.
