### ISSUE TITLE
Request is malformed - can't do advanced trading - 1.4.1

### ISSUE THREAD

**Issue by Devnant** [rippex/ripple-client-desktop#16]
Whenever I try to do any trading on the advanced tab the following error message appears: 

"Your request is invalid, reason: temREDUNDANT - Sends same currency to self."

I'm trying to trade the XRP/BRL pair

**Comment by marsface** [comment]
If you fill the fields in the "top down" order, this won't happen. If you edited the last field after filling the previous you might get this error. After editing the last field please go to the first again and remove decimal places until there is only 6 left.
