### ISSUE TITLE
Ripple Desktop Wallet

### ISSUE THREAD

**Issue by crpiep** [rippex/ripple-client-desktop#24]
Downloaded Ripple Desktop Wallet and setup an account with a password. I wrote the password down and the secret key. I deposited quite a few XRP in. After Log Out its impossible to login...LOGIN FAILED WALLET FILE OR PASSWORD WRONG. How do I get in my Wallet ??? I have The Key and Password. I am not Technical, can Anyone Help ???

**Comment by Aquilae32** [comment]
Suggestion: Before entering your password, make sure you select the right account file (Ripple_Wallet to transact or Ripple_Wallet-Regular for read only).

I am not Technical either.

**Comment by markob17** [comment]
Try creating new account using the create new account>create a new account with a secret key option. Input your secret key and click create new account button. I tried this and it works. As long as you have your secret key, should be able to create a new account. If this doesn't work on your current workstation, try installing the ripple desktop wallet on another computer and perform the same steps - maybe your installation got corrupt.

**Comment by crpiep** [comment]
Thank U

**Comment by markob17** [comment]
I also tried the following old version of a ripple client found on github and followed the above steps using my secret key and it also let me create a new wallet. Idk why it wouldn't be working for you guys. Maybe give this old version a try. 
https://github.com/yxxyun/ripple-client-desktop/releases/download/ripple-client-desktop-v1.0.29/packages.zip

**Comment by marsface** [comment]
#23

**Comment by Steliron** [comment]
Where I can download ripple desktop wallet?

**Comment by Aquilae32** [comment]
The rippex Ripple Desktop Wallet is available for download at [https://rippex.net/carteira-ripple.php#/](url)
