### ISSUE TITLE
Desktop wallet ripple doesnt send my ripples to exchange saying I have no funds

### ISSUE THREAD

**Issue by gusbertol** [rippex/ripple-client-desktop#37]
I have 133 xrp in the desktop wallet, but they will not let me say that there are no funds, what is happening?

**Comment by gusbertol** [comment]
the problem is the reserve, i didn't knew about this, have a way to avoid this?

**Comment by werewere** [comment]
Same problem here. I'm trying to send about 1000 XRP and it says that there are no funds (And I have 2000 XRP in the wallet). It can't be the reserve in my case, as it is supposed to be only 20XRP

**Comment by marsface** [comment]
Hello, it is a sync issue, just logout and log back in in order to solve the problem.
