### ISSUE TITLE
Rand wallet file corruption 1 out of 3 gets corrupted

### ISSUE THREAD

**Issue by cybertrack131** [rippex/ripple-client-desktop#93]
I need help to recover my wallet, I made some tests and noticed that 1 out of 3 newly created wallets gets corrupted and you can't open them, i used always same password from notepad copy/paste.

The start point would be to check how Rippex does the encryption of my wallet file with the correct password and then try to decrypt it manually to first see if the Ripple adress is correct and then try to recover the secret key.

PS : I have my wallet file, the correct password for it but I don't have my secret key, here is an example of how it cannot open the wallet file using the correct password "azerty12"

![creation](https://user-images.githubusercontent.com/24479236/34457819-3f172194-edbd-11e7-8a53-600321f6a9a7.jpg)

![login error](https://user-images.githubusercontent.com/24479236/34457820-3f3a1ed8-edbd-11e7-9396-ce0b86e8f3d6.jpg)

the corrupted wallet file :

eyJpdiI6InNpRXlyUzByajZCQUI4T2VCZFNqcFE9PSIsInYiOjEsIml0ZXIiOjEwMDAsImtzIjoyNTYsInRzIjo2NCwibW9kZSI6ImNjbSIsImFkYXRhIjoiIiwiY2lwaGVyIjoiYWVzIiwic2FsdCI6IjlvKzh2a1ZpbjhrPSIsImN0IjoiRHF1STlZeGtlZmxHMytoNmNLbGhoVkZDVTVZNGJGMVBraTVFV2VvZTFVTzNvaGdMQktHbHlPRmZkMm1OWndhVFJmczA2bm51UXFHbHdaRzlnb0RLTjI0R0M3SVZlK1B4QTRqRGlNakhrMjcvQWVNSmd3NjN4azR0YXVLRHY1N0NHYVZad2tnMjNHQXdISmtPcXFsWmZyc1VBODR3bFpXWWFaWjJmVEdpNkJYK2pjNUEwZklCaEdxb0Z5cjJKeDJ1TXRIc1h4aXVMcGt0TDZUZ2NzV2l2QVpES3JUNGJ3QnlhL3hBSENzMmt4Z2NTQ1pnIn0=VVdveVR0K0I3MUx1b0lXSEg4NjNSOEVyaW9RPT0ifQ==

**Comment by shayanb** [comment]
@cybertrack131 it seems like the correct wallet file is this:

```
eyJpdiI6InNpRXlyUzByajZCQUI4T2VCZFNqcFE9PSIsInYiOjEsIml0ZXIiOjEwMDAsImtzIjoyNTYsInRzIjo2NCwibW9kZSI6ImNjbSIsImFkYXRhIjoiIiwiY2lwaGVyIjoiYWVzIiwic2FsdCI6IjlvKzh2a1ZpbjhrPSIsImN0IjoiRHF1STlZeGtlZmxHMytoNmNLbGhoVkZDVTVZNGJGMVBraTVFV2VvZTFVTzNvaGdMQktHbHlPRmZkMm1OWndhVFJmczA2bm51UXFHbHdaRzlnb0RLTjI0R0M3SVZlK1B4QTRqRGlNakhrMjcvQWVNSmd3NjN4azR0YXVLRHY1N0NHYVZad2tnMjNHQXdISmtPcXFsWmZyc1VBODR3bFpXWWFaWjJmVEdpNkJYK2pjNUEwZklCaEdxb0Z5cjJKeDJ1TXRIc1h4aXVMcGt0TDZUZ2NzV2l2QVpES3JUNGJ3QnlhL3hBSENzMmt4Z2NTQ1pnIn0=
```

**Comment by cybertrack131** [comment]
If you created the wallet file from the secret key, then it doesn't help me much...

**Comment by cybertrack131** [comment]
YOU SAVED ME THANK YOU
